export { antiSlop } from './configs/anti-slop.ts'
export { disables } from './configs/disables.ts'
export { astro, svelte, vue } from './configs/frameworks.ts'
export { ignores } from './configs/ignores.ts'
export { javascript } from './configs/javascript.ts'
export { react } from './configs/react.ts'
export { test } from './configs/test.ts'
export { typescript } from './configs/typescript.ts'
export { saiful, saiful as default } from './factory.ts'
export * from './globs.ts'
export type { OptionsConfig, OptionsOverrides, Rules } from './types.ts'
export { isInEditorEnv, mergeConfigs } from './utils.ts'
